version: "3"
services:
  my-app:
    build: .
    ports:
      - "80:80"
<<<<<<< HEAD
      
=======

>>>>>>> 462a61759fc14cedafeabfc51de37f34a986f62c
  db:
    image: "postgres:11"
    container_name: "postgres_database"
    environment:
      - POSTGRES_PASSWORD=berkcihancengiz
      - POSTGRES_USER=cihan
      - POSTGRES_DB=stories
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
